FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}

ENABLE_PROXY_FIX = True
SECRET_KEY = "53wclGt2t78CLV3O0meSL8K6ivdSbpkQeDyOSLbPLuMqHY/r7HwuyLq7"

# Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = False
